variable "prefix" {
  type        = string
  description = "A prefix to be used for naming the Lambda function and its associated IAM role."
}

variable "hash_length" {
  type        = number
  default     = 6
  description = "The length of the hash to be generated by the Lambda function."
}

variable "max_hash_attempts" {
  type        = number
  default     = 10
  description = "The maximum number of attempts the Lambda function should make to generate a unique hash."
}

variable "table_arn" {
  type        = string
  description = "The ARN of the DynamoDB table the Lambda function will interact with."
}

variable "private_subnets_ids" {
  type        = list(string)
  description = "The ids for the subnets"
}

variable "lambda_kms_key_arn" {
  type        = string
  description = "KMS key ARN used to encrypt Lambda environment variables"
}

variable "vpc_id" {
  type        = string
  description = "VPC ID where the Lambda security group will be created"
}